src/Webtek/EcommerceBundle/Entity/Brand.php
<?php
// 09/01/17, 16.18
// @author : Giovanni Battista Lenoci <gianiaz@gmail.com>
namespace Webtek\EcommerceBundle\Entity;

use AppBundle\Traits\Loggable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;
use Knp\DoctrineBehaviors\Model as ORMBehaviours;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use AppBundle\Validator\Constraints as WebTekAssert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="Webtek\EcommerceBundle\Repository\BrandsRepository")
 * @ORM\Table(name="brands")
 * @Vich\Uploadable()
 */
class Brand
{

    use ORMBehaviours\SoftDeletable\SoftDeletable, ORMBehaviours\Timestampable\Timestampable, ORMBehaviours\Translatable\Translatable, Loggable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="boolean")
     */
    private $isEnabled;

    /**
     * @ORM\Column(type="integer")
     */
    private $sort;

    /**
     * @Vich\UploadableField(mapping="brands", fileNameProperty="listImgFileName")
     */
    private $listImg;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $listImgFileName;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $listImgAlt;

    private $listImgData;
    private $listImgDelete;


    private $uuid;

    public function __construct()
    {

        $this->setUuid(Uuid::uuid1());
        $this->setSort(0);

    }

    /**
     * @return mixed
     */
    public function getId()
    {

        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getIsEnabled()
    {

        return $this->isEnabled;
    }

    /**
     * @param mixed $isEnabled
     */
    public function setIsEnabled($isEnabled)
    {

        $this->isEnabled = $isEnabled;
    }

    public function __toString()
    {

        return (string)$this->translate()->getTitolo();
    }

    /**
     * @return mixed
     */
    public function getUuid()
    {

        return $this->uuid;
    }

    /**
     * @param mixed $uuid
     */
    public function setUuid($uuid)
    {

        $this->uuid = $uuid;
    }

    /**
     * @return mixed
     */
    public function getSort()
    {

        return $this->sort;
    }

    /**
     * @param mixed $sort
     */
    public function setSort($sort)
    {

        $this->sort = $sort;
    }


    public function getListImgFileName()
    {

        return $this->listImgFileName;
    }

    /**
     * @param mixed $listImgFileName
     */
    public function setListImgFileName($listImgFileName)
    {

        $this->listImgFileName = $listImgFileName;
    }

    /**
     * @return mixed
     */
    public function getListImgAlt()
    {

        return $this->listImgAlt;
    }

    /**
     * @param mixed $listImgAlt
     */
    public function setListImgAlt($listImgAlt)
    {

        $this->listImgAlt = $listImgAlt;
    }

    /**
     * @return File
     */
    public function getListImg()
    {

        return $this->listImg;
    }

    /**
     * @return Brand
     */
    public function setListImg($listImg = null)
    {

        $this->listImg = $listImg;
        $this->updatedAt = new \DateTimeImmutable();

        return $this;

    }

    /**
     * @return mixed
     */
    public function getListImgDelete()
    {

        return $this->listImgDelete;
    }

    /**
     * @param mixed $listImgDelete
     */
    public function setListImgDelete($listImgDelete)
    {

        $this->listImgDelete = $listImgDelete;
    }

    /**
     * @return mixed
     */
    public function getListImgData()
    {

        return $this->listImgData;
    }

    /**
     * @param mixed $listImgData
     */
    public function setListImgData($listImgData)
    {

        $this->listImgData = $listImgData;
    }


    function getUploadDir()
    {

        return 'files/brands/' . $this->getId() . '/';

    }

}

src/Webtek/EcommerceBundle/Form/OrderForm.php
<?php
// 12/06/17, 11.02
// @author : Giovanni Battista Lenoci <gianiaz@gmail.com>

namespace Webtek\EcommerceBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Webtek\EcommerceBundle\Entity\Order;

class OrderForm extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->add(
            'status',
            EntityType::class,
            [
                'class' => 'Webtek\EcommerceBundle\Entity\OrdersStatus',
                'label' => 'order.labels.stato_ordine',
                'required' => true,
            ]
        );

        $builder->add(
            'payment',
            EntityType::class,
            [
                'class' => 'Webtek\EcommerceBundle\Entity\MetodiPagamento',
                'label' => 'order.labels.metodo_pagamento',
                'required' => true,
            ]
        );

        $builder->add(
            'pagato',
            ChoiceType::class,
            [
                'label' => 'order.labels.pagato',
                'choices' => [
                    'default.labels.si' => true,
                    'default.labels.no' => false,
                ],
                'placeholder' => false,
                'required' => false,
            ]
        );


        $builder->add(
            'transactionId',
            TextType::class,
            [
                'label' => 'order.labels.transaction_id',
                'help' => 'order.help.transaction_id',
            ]
        );
        //$builder->add('payedAmount', TextType::class, ['label' => 'order.labels.payed_amount']);

    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults(
            [
                'data_class' => Order::class,
                'error_bubbling' => true,
                'langs' => [
                    'it' => 'Italiano',
                ],
            ]
        );

    }


}

src/Webtek/EcommerceBundle/Controller/Admin/OrderController.php
<?php

namespace Webtek\EcommerceBundle\Controller\Admin;

use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Knp\DoctrineBehaviors\ORM\SoftDeletable\SoftDeletableSubscriber;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Webtek\EcommerceBundle\Entity\Order;
use Webtek\EcommerceBundle\Form\OrderForm;

/**
 * @Route("/admin")
 * @Security("is_granted('ROLE_MANAGE_ECOMMERCE_ORDER')")
 */
class OrderController extends Controller
{

    /**
     * @Route("/order", name="order")
     */
    public function listAction()
    {

        return $this->render('@WebtekEcommerce/admin/order/list.html.twig');

    }

    /**
     * @Route("/order/json", name="order_list_json")
     */
    public function listJson(Request $request)
    {

        $em = $this->getDoctrine()->getManager();

        $return = [];
        $return['result'] = true;
        $return['data'] = $this->get('app.webtek_ecommerce.services.order_helper')->getList(
            $this->isGranted('ROLE_RESTORE_DELETED')
        );

        return new JsonResponse($return);

    }

    /**
     * @Route("/order/edit/{id}",  name="order_edit", requirements={"id": "\d+"})
     */
    public function editAction(Request $request)
    {

        $langs = $this->get('app.languages')->getActiveLanguages();
        $translator = $this->get('translator');

        $em = $this->getDoctrine()->getManager();

        $Order = new Order();

        $id = null;

        if ($request->get('id')) {

            $id = $request->get('id');

            $Order = $em->getRepository('WebtekEcommerceBundle:Order')->findOneBy(['id' => $id]);

            $oldStatus = $Order->getStatus();

            if (!$Order) {

                $this->addFlash(
                    'error',
                    'Ordine n. ' . $request->get('id') . ' ' . $translator->trans('default.labels.non_trovato')
                );

                return $this->redirectToRoute('order');
            }

        }

        $form = $this->createForm(
            OrderForm::class,
            $Order,
            ['langs' => $langs]
        );

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            /**
             * @var $OrderOrder
             */
            $Order = $form->getData();

            $em->persist($Order);
            $em->flush();

            $NewStatus = $Order->getStatus();

//            if ($oldStatus != $NewStatus || 1) {
//                $orderHelper = $this->get('app.webtek_ecommerce.services.order_helper');
//                $orderHelper->manageChangedStatus($Order);
//            }
            $em->persist($Order);
            $em->flush();

            $this->addFlash('success',
                'Ordine n. ' . $Order->getId() . ' ' . $translator->trans('default.labels.salvato'));


            return $this->redirectToRoute('order');

        }

        $view = '@WebtekEcommerce/admin/order/edit.html.twig';

        return $this->render($view, ['form' => $form->createView(), 'order' => $Order]);


    }

    /**
     * @Route("/order/send-mail/{id}",  name="order_mail", requirements={"id": "\d+"})
     */
    public function sendMail(Request $request)
    {

        $em = $this->getDoctrine()->getManager();

        $Order = new Order();

        $id = null;

        if ($request->get('id')) {

            $id = $request->get('id');

            $Order = $em->getRepository('WebtekEcommerceBundle:Order')->findOneBy(['id' => $id]);

            $oldStatus = $Order->getStatus();

            if (!$Order) {

                $this->addFlash(
                    'error',
                    'Ordine n. ' . $request->get('id') . ' ' . $translator->trans('default.labels.non_trovato')
                );

                return $this->redirectToRoute('order');
            }

        }

        $this->get('app.webtek_ecommerce.services.order_helper')->sendMailOrder($Order);

        return new Response('<body></body>');

    }

    /**
     * @Route("/order/statistiche",  name="order_stats")
     */
    public function statisticheAction(Request $request)
    {

        return $this->render(
            '@WebtekEcommerce/admin/order/statistiche.html.twig',
            []
        );

    }

    /**
     * @Route("/order/statistiche-anno",  name="order_stats_year")
     */
    public function statisticheAnno(Request $request)
    {

        $orderHelper = $this->get('app.webtek_ecommerce.services.order_helper');
        $stats = $orderHelper->getStatisticheAnnue();

        $data = [];

        foreach ($stats as $anno => $totali) {

            $record = array_merge(['y' => $anno], $totali);

            $data[] = $record;

        }

        $return = [];
        $return['result'] = true;
        $return['data'] = $data;

        return new JsonResponse($return);

    }

    /**
     * @Route("/order/statistiche-mese",  name="order_stats_month")
     */
    public function statisticheMese(Request $request)
    {

        $orderHelper = $this->get('app.webtek_ecommerce.services.order_helper');

        $stats = $orderHelper->getStatisticheMensili();

        $data = [];

        foreach ($stats as $periodo => $totali) {

            $record = array_merge(['y' => $periodo], $totali);

            $data[] = $record;

        }

        $return = [];
        $return['result'] = true;
        $return['data'] = $data;

        return new JsonResponse($return);

    }

}

src/Webtek/EcommerceBundle/Resources/views/admin/order/edit.html.twig
{% extends "@WebtekEcommerce/admin/order/formLayout.html.twig" %}

{% block title %} {% trans %} order.labels.title{% endtrans %}: {% trans %} default.labels.modifica{% endtrans %} {% endblock %}
{% block page_title %} {% trans %} order.labels.title{% endtrans %}: {% trans %} default.labels.modifica{% endtrans %} {% endblock %}

src/Webtek/EcommerceBundle/Resources/views/admin/order/form.html.twig
{{ form_start(form) }}

{{ form_errors(form) }}

<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2>{% trans %} order.labels.dettaglio_ordine {% endtrans %}</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            {% if order %}

                <table class="table-responsive table">
                    <thead>
                    <tr>
                        <th colspan="3">{{ order.billing | nl2br }}</th>
                        <th colspan="2" class="delivery">{{ order.delivery | nl2br }}</th>
                    </tr>
                    <tr>
                        <th></th>
                        <th>{% trans %}ecommerce.labels.prodotto{% endtrans %}</th>
                        <th class="numeric">{% trans %}ecommerce.labels.prezzo{% endtrans %}</th>
                        <th class="qty">{% trans %}ecommerce.labels.quantita{% endtrans %}</th>
                        <th class="numeric">{% trans %}ecommerce.labels.subtotale{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for riga in order.records %}
                        <tr>
                            <td>
                                {% if riga.product %}
                                    <img src="{{ asset(riga.product.uploadDir ~ riga.product.listImgFileName) | imagine_filter('product_mini') }}"
                                         alt="{{ riga.product.listImgAlt }}"/>
                                {% endif %}
                            </td>
                            <td>{% if ecommerce.manage_brands %}{{ riga.product.brand }}
                                    <br/>{% endif %}{{ riga.product }}
                                {% if riga.variante %}
                                    <br/>{{ riga.variante }}
                                {% endif %}
                                <br/>
                                Rif. {{ riga.code }}
                            </td>
                            <td class="numeric">{{ taxCalculator.getPrezzoIvato(riga.prezzo, riga.tax)| localizedcurrency('EUR') }}</td>
                            <td class="qty">
                                {{ riga.qty }}
                            </td>
                            <td class="numeric">{{ (taxCalculator.getPrezzoIvato(riga.prezzo, riga.tax) * riga.qty) | localizedcurrency('EUR') }}</td>
                        </tr>
                    {% endfor %}
                    {% if order.couponScontoEuro == "0.00" and order.couponDescription %}
                        <tr>
                            <td class="numeric" colspan="5">
                                {{ order.couponDescription }}
                            </td>
                        </tr>
                    {% endif %}

                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="4" class="numeric">
                            {% trans %}ecommerce.labels.imponibile{% endtrans %}
                        </td>
                        <td class="numeric">{{ orderHelper.getImponibile(order) | localizedcurrency('EUR') }}</td>
                    </tr>
                    {% for tasse in orderHelper.getTasse(order) %}
                        <tr>
                            <td colspan="4" class="numeric">
                                {{ tasse.description }}
                            </td>
                            <td class="numeric">{{ tasse.imposta | localizedcurrency('EUR') }}</td>
                        </tr>
                    {% endfor %}
                    {% if order.deliveryCost %}
                        <tr>
                            <td colspan="4" class="numeric">
                                {{ order.deliverBy }}
                            </td>
                            <td class="numeric">{{ order.deliveryCost | localizedcurrency('EUR') }}</td>
                        </tr>
                    {% endif %}
                    {% if order.couponScontoEuro > 0 %}
                        <tr>
                            <td colspan="4" class="numeric">
                                {% trans %}ecommerce.labels.subtotaletotale{% endtrans %}
                            </td>
                            <td class="numeric">{{ (order.total + order.deliveryCost + order.couponScontoEuro) | localizedcurrency('EUR') }}</td>
                        </tr>
                        <tr>
                            <td class="numeric" colspan="4">
                                {{ order.couponDescription }}
                            </td>
                            <td class="numeric">
                                - {{ order.couponScontoEuro|localizedcurrency("EUR") }}
                            </td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td colspan="4" class="numeric">
                            {% trans %}ecommerce.labels.totale{% endtrans %}
                        </td>
                        <td class="numeric">{{ (order.total + order.deliveryCost) | localizedcurrency('EUR') }}</td>
                    </tr>
                    </tfoot>
                    </tbody>

                </table>
            {% endif %}
        </div>
    </div>

    <div class="x_panel">
        <div class="x_title">
            <h2>{% trans %} order.labels.stato_ordine {% endtrans %}</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            {{ form_row(form.status) }}
            {{ form_row(form.payment) }}
            {{ form_row(form.pagato) }}
            {{ form_row(form.transactionId) }}

        </div>
    </div>
</div>

<div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3 col-sm-offset-3">

    <button type="submit" class="btn btn-success" formnovalidate><i class="fa fa-save"></i> {% trans %}
            default.labels.salva {% endtrans %}</button>

    <a href="{{ path('order') }}" class="btn btn-danger"><i class="fa fa-close"></i> {% trans %}
            default.labels.chiudi {% endtrans %}</a>
</div>

</div>

{{ form_end(form) }}

src/Webtek/EcommerceBundle/Resources/views/admin/order/formLayout.html.twig
{% extends "admin/admin.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('public/lib/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.css') }}" rel="stylesheet">
    <link href="{{ asset('bundles/webtekecommerce/admin/css/order.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('public/lib/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('bundles/webtekecommerce/admin/js/order.js') }}"></script>
{% endblock %}

{% block page_content %}
    {{ include('@WebtekEcommerce/admin/order/form.html.twig') }}
{% endblock %}

src/Webtek/EcommerceBundle/Resources/views/admin/order/list.html.twig
{% extends "admin/admin-list.html.twig" %}

{% block page_title %} {% trans %} order.labels.title{% endtrans %}: {% trans %} default.labels.elenco{% endtrans %} {% endblock %}

{% block pulsantiera %}
    <div class="btn-group" role="group">
        <a href="{{ path("order_stats") }}" class="btn btn-primary"><i class="fa fa-area-chart"></i> {% trans %}
                order.labels.statistiche {% endtrans %}
        </a>
    </div>
{% endblock %}

{% block page_content %}
    <div class="x_panel">
        <div class="x_content">
            <table data-name="datatable" id="datatable" class="table table-striped table-bordered">
            </table>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/webtekecommerce/admin/js/order.js') }}"></script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/webtekecommerce/admin/css/order.css') }}" rel="stylesheet">
{% endblock %}

src/Webtek/EcommerceBundle/Resources/views/admin/order/statistiche.html.twig
{% extends "admin/admin.html.twig" %}

{% block title %} {% trans %} order.labels.title{% endtrans %}: {% trans %} order.labels.statistiche{% endtrans %} {% endblock %}
{% block page_title %} {% trans %} order.labels.title{% endtrans %}: {% trans %} order.labels.statistiche{% endtrans %} {% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/webtekecommerce/admin/css/order.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/vendors/morris.js/morris.css') }}" rel="stylesheet">

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/webtekecommerce/admin/js/order.js') }}"></script>
    <script src="{{ asset('admin/vendors/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('admin/vendors/morris.js/morris.min.js') }}"></script>
{% endblock %}

{% block page_content %}
    <h2>{% trans %} order.labels.statistiche_annue{% endtrans %}</h2>
    <div id="ordini-annui" style="height: 250px;"></div>
    <h2>{% trans %} order.labels.statistiche_mensili{% endtrans %}</h2>
    <div id="ordini-mensili" style="height: 250px;"></div>
{% endblock %}